version: '3.1'

services:
  
  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=pjsuporte
      - MYSQL_USER=example
      - MYSQL_PASSWORD=example
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db: