"""empty message

Revision ID: 3ef1de772370
Revises: 19719ab5254d
Create Date: 2023-06-23 00:50:11.287509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ef1de772370'
down_revision = '19719ab5254d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solicitacao_cadastros', sa.Column('data', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('solicitacao_cadastros', 'data')
    # ### end Alembic commands ###
