"""empty message

Revision ID: 797151f4929b
Revises: fde15ff0d4d0
Create Date: 2023-07-10 11:26:24.788226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '797151f4929b'
down_revision = 'fde15ff0d4d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emails_informativos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('enviante', sa.String(length=64), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emails_informativos_enviante'), 'emails_informativos', ['enviante'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emails_informativos_enviante'), table_name='emails_informativos')
    op.drop_table('emails_informativos')
    # ### end Alembic commands ###
