"""empty message

Revision ID: 7c809aecec59
Revises: f9957f01576a
Create Date: 2022-08-26 12:22:47.396477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c809aecec59'
down_revision = 'f9957f01576a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chamados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('data', sa.String(length=64), nullable=True),
    sa.Column('cpf', sa.String(length=64), nullable=False),
    sa.Column('nome', sa.String(length=64), nullable=False),
    sa.Column('sistema', sa.String(length=64), nullable=True),
    sa.Column('entidade', sa.String(length=120), nullable=True),
    sa.Column('assunto', sa.String(length=120), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('detalhes', sa.Text(), nullable=False),
    sa.Column('solucao', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chamados_assunto'), 'chamados', ['assunto'], unique=False)
    op.create_index(op.f('ix_chamados_author'), 'chamados', ['author'], unique=False)
    op.create_index(op.f('ix_chamados_cpf'), 'chamados', ['cpf'], unique=False)
    op.create_index(op.f('ix_chamados_data'), 'chamados', ['data'], unique=False)
    op.create_index(op.f('ix_chamados_nome'), 'chamados', ['nome'], unique=False)
    op.create_index(op.f('ix_chamados_sistema'), 'chamados', ['sistema'], unique=False)
    op.create_index(op.f('ix_chamados_status'), 'chamados', ['status'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpf', sa.String(length=64), nullable=False),
    sa.Column('nome', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_cpf'), 'users', ['cpf'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_nome'), 'users', ['nome'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_nome'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_cpf'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_index(op.f('ix_chamados_status'), table_name='chamados')
    op.drop_index(op.f('ix_chamados_sistema'), table_name='chamados')
    op.drop_index(op.f('ix_chamados_nome'), table_name='chamados')
    op.drop_index(op.f('ix_chamados_data'), table_name='chamados')
    op.drop_index(op.f('ix_chamados_cpf'), table_name='chamados')
    op.drop_index(op.f('ix_chamados_author'), table_name='chamados')
    op.drop_index(op.f('ix_chamados_assunto'), table_name='chamados')
    op.drop_table('chamados')
    # ### end Alembic commands ###
