"""empty message

Revision ID: fde15ff0d4d0
Revises: 3ef1de772370
Create Date: 2023-06-29 20:06:46.583281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fde15ff0d4d0'
down_revision = '3ef1de772370'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solicitacao_cadastros', sa.Column('permissao', sa.String(length=64), nullable=False))
    op.create_index(op.f('ix_solicitacao_cadastros_permissao'), 'solicitacao_cadastros', ['permissao'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_solicitacao_cadastros_permissao'), table_name='solicitacao_cadastros')
    op.drop_column('solicitacao_cadastros', 'permissao')
    # ### end Alembic commands ###
